# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
DeepSeek V3.2 PaddleFleet model bridge.

This module bridges the HuggingFace-style PretrainedConfig/PretrainedModel
interface used by PaddleFormers with the PaddleFleet provider system.

Pattern follows glm_moe_dsa/modeling.py (GLM5 PR #3940) exactly:
  - DeepseekV32ForCausalLM.__new__() calls DeepSeekV3_2BaseProvider.from_config(config)
  - provider.provide() calls paddlefleet.gpt_builders.gpt_builder()
  - Returns a PaddleFleet GPT model (Megatron-style)
"""

import os
import sys

from ..aoa_config_base import MoEAOAConfigGenerator
from ..model_utils import PretrainedModel
from .configuration import DeepseekV32Config


class DeepseekV32PreTrainedModel(PretrainedModel):
    config_class = DeepseekV32Config
    base_model_prefix = "model"

    # Layernorm weight names that need dtype cast (fleet model skips generic dtype mapping)
    _NORM_WEIGHT_KEYS = (
        "input_layernorm.weight",
        "post_attention_layernorm.weight",
        "q_a_layernorm.weight",
        "kv_a_layernorm.weight",
        "k_norm.weight",
        "k_norm.bias",
        "norm.weight",
    )

    @classmethod
    def _gen_aoa_config(cls, config: DeepseekV32Config):
        aoa_config = MoEAOAConfigGenerator.gen_aoa_config(config)
        cls._inject_norm_dtype(aoa_config["aoa_statements"], "bfloat16")
        return aoa_config

    @classmethod
    def _gen_inv_aoa_config(cls, config: DeepseekV32Config):
        inv_aoa_config = MoEAOAConfigGenerator.gen_inv_aoa_config(config)
        cls._inject_norm_dtype(inv_aoa_config["aoa_statements"], "float32")
        return inv_aoa_config

    @classmethod
    def _inject_norm_dtype(cls, aoa_statements, target_dtype):
        """Inject dtype into existing layernorm statements generated by base class."""
        for i, stmt in enumerate(aoa_statements):
            if any(k in stmt for k in cls._NORM_WEIGHT_KEYS) and "dtype=" not in stmt:
                aoa_statements[i] = f"{stmt}, dtype='{target_dtype}'"


def _build_model(config):
    """
    Common __new__ logic shared by ForCausalLM and ForCausalLMPipe.

    Steps:
    1. Normalise parallel config attributes (same as GLM5).
    2. Call DeepSeekV3_2BaseProvider.from_config(config) to populate provider fields.
    3. Call provider.provide() which runs gpt_builder() and returns the PaddleFleet model.
       (moe_layer_freq + first_k_dense_replace conversion is handled by
        TransformerConfig.__post_init__ automatically.)
    """
    # 1. Normalise parallel config (guard against missing attrs from old configs)
    config.tensor_model_parallel_size = max(getattr(config, "tensor_model_parallel_size", 1), 1)
    config.pipeline_model_parallel_size = max(getattr(config, "pipeline_model_parallel_size", 1), 1)
    config.context_parallel_size = max(getattr(config, "context_parallel_size", 1), 1)
    config.virtual_pipeline_model_parallel_size = max(getattr(config, "virtual_pipeline_model_parallel_size", 1), 1)
    config.expert_model_parallel_size = max(getattr(config, "expert_model_parallel_size", 1), 1)

    # 2. Resolve provider module path.
    #    The provider lives under examples/experiments/paddlefleet/ which is
    #    not a proper package. We add it to sys.path if needed.
    _provider_dir = os.path.join(
        os.path.dirname(__file__),  # .../paddleformers/transformers/deepseek_v32/
        "..",
        "..",
        "..",
        "examples",
        "experiments",
        "paddlefleet",
    )
    _provider_dir = os.path.normpath(_provider_dir)
    if _provider_dir not in sys.path:
        sys.path.insert(0, _provider_dir)

    from deepseek_v3_2_provider import DeepSeekV3_2BaseProvider

    # 3. Build model via provider
    model_provider = DeepSeekV3_2BaseProvider.from_config(config)
    gpt_model = model_provider.provide()
    gpt_model.config_to_save = config
    return gpt_model


class DeepseekV32ForCausalLM(DeepseekV32PreTrainedModel):
    """DeepSeek V3.2 model for pipeline_model_parallel_size == 1."""

    is_fleet = True

    def __new__(cls, config):
        gpt_model = _build_model(config)
        gpt_model.is_fleet = cls.is_fleet
        gpt_model._gen_aoa_config = cls._gen_aoa_config
        gpt_model._gen_inv_aoa_config = cls._gen_inv_aoa_config
        return gpt_model


class DeepseekV32ForCausalLMPipe(DeepseekV32PreTrainedModel):
    """DeepSeek V3.2 model for pipeline_model_parallel_size > 1."""

    is_fleet = True

    def __new__(cls, config):
        if not hasattr(config, "architectures"):
            config.architectures = ["DeepseekV32ForCausalLM"]
        gpt_model = _build_model(config)
        gpt_model.is_fleet = cls.is_fleet
        gpt_model._gen_aoa_config = cls._gen_aoa_config
        gpt_model._gen_inv_aoa_config = cls._gen_inv_aoa_config
        return gpt_model


__all__ = [
    "DeepseekV32PreTrainedModel",
    "DeepseekV32ForCausalLM",
    "DeepseekV32ForCausalLMPipe",
]
