name: Build CI-Docker Images

on:
  push:
    branches: [develop]
    paths:
      - "requirements*"
      - "tests/requirements.txt"
      - "setup.py"
      - ".github/workflows/build-ci-docker-images.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]
    paths:
      - "requirements*"
      - "tests/requirements.txt"
      - "setup.py"
      - ".github/workflows/build-ci-docker-images.yml"
  schedule:
    - cron: "5 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  BRANCH: ${{ github.event.pull_request.base.ref }}
  no_proxy: "localhost,bj.bcebos.com,su.bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

jobs:
  build-ci-docker-images:
    name: build-ci-docker-images
    runs-on: [self-hosted, 4gpu]
    outputs:
      image_name: ${{ steps.set_image_name.outputs.image_name }}
  
    steps:
      - name: Download Code
        env:
          work_dir: ${{ github.workspace }}
        run: |
          sudo rm -rf * .[^.]*
          wget -q --no-proxy  https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddleFormers.tar --no-check-certificate
          echo "Extracting PaddleFormers.tar.gz"
          tar xf PaddleFormers.tar && rm -rf PaddleFormers.tar
          source ${{ github.workspace }}/../../../proxy
          cd PaddleFormers
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git submodule update --init --recursive --force
          if [ -n "${PR_ID}" ]; then
            git fetch origin pull/${PR_ID}/head
            git checkout -b PR_${PR_ID} FETCH_HEAD
            git remote add upstream https://github.com/PaddlePaddle/PaddleFormers.git
            git fetch upstream ${BRANCH}
            git merge ${BRANCH}
            git diff --numstat ${BRANCH} -- | awk '{print $NF}'
          else
            echo "Not in a pull_request event. Skipping PR-specific operations."
          fi
          git log --pretty=oneline -10

      - name: Write Dockerfile Inline
        env:
          work_dir: ${{ github.workspace }}/PaddleFormers
        run: |
          cat <<EOF > Dockerfile
          FROM iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-libsndfile
          RUN unlink /usr/bin/python3 && ln -sf python3.10 /usr/bin/python3
          RUN python -m pip config --user set global.index http://pip.baidu-int.com/search/
          RUN python -m pip config --user set global.index-url http://pip.baidu-int.com/simple
          RUN python -m pip config --user set global.trusted-host pip.baidu-int.com
          RUN python -m pip install bce-python-sdk==0.8.74
          RUN python -m pip install --no-cache-dir https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuSome-LinuxCentos-Gcc82-Cuda118-Cudnn86-Trt85-Py310-CINN-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          COPY PaddleFormers/ /tmp/paddleformers/
          WORKDIR /tmp/paddleformers
          RUN python -m pip install -r requirements.txt
          RUN python -m pip install -r requirements-dev.txt
          RUN python -m pip install -r tests/requirements.txt
          RUN python setup.py bdist_wheel > /dev/null
          RUN python -m pip install dist/*.whl
          WORKDIR /
          RUN rm -rf /tmp/paddleformers
          CMD ["python3"]
          EOF
      
      - name: Set Image Name
        id: set_image_name
        run: |
          if [[ "${{ github.event_name }}" =~ ^(push|schedule)$ ]]; then
            image_name=iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-latest
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            image_name=iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-${PR_ID}-${COMMIT_ID}
          fi
          echo "image_name=${image_name}" >> ${{ github.env }}
          echo "image_name=${image_name}" >> "$GITHUB_OUTPUT"
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.image_name }} .

  test-ci-docker-images:
    name: test-ci-docker-images
    if: github.event_name == 'pull_request'
    needs: build-ci-docker-images
    uses: ./.github/workflows/unittest-gpu.yml
    with:
      image_name: ${{ needs.build-ci-docker-images.outputs.image_name }}

  clean-ci-image:
    needs: test-ci-docker-images
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, 4gpu]
    steps:
      - name: Remove CI Image
        run: |
          image_name="iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-${PR_ID}-${COMMIT_ID}"
          CONTAINERS=$(docker ps -a --filter "ancestor=$image_name" --format "{{.ID}}")

          if [ -z "$CONTAINERS" ]; then
              echo "$image_name is not using by any container, deleting..."
              docker rmi "$image_name"
          else
              echo "$image_name is using by containers:"
              echo "$CONTAINERS"
          fi

          # 安全删除悬空镜像（无悬空镜像时跳过）
          docker images -f "dangling=true" -q | xargs -r docker rmi -f