name: Debug Unittest GPU with SSH

on:
  workflow_dispatch:

env:
  PR_ID: ${{ github.event.pull_request.number }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  BRANCH: ${{ github.event.pull_request.base.ref }}
  AGILE_COMPILE_BRANCH: ${{ github.event.pull_request.base.ref }}
  TASK: PaddleFormers-CI-${{ github.event.pull_request.number }}-unittest-gpu-debug
  ci_scripts: /workspace/PaddleFormers/scripts/unit_test
  CI_name: unittest-gpu-debug
  no_proxy: "localhost,bj.bcebos.com,su.bcebos.com,bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
  HF_ENDPOINT: https://hf-mirror.com
  STUDIO_GIT_HOST: http://git.prod.idc-to-cloud.aistudio.baidu-int.com
  PPNLP_HOME: /ssd1/PaddleNLP
  HF_DATASETS_CACHE: /ssd1/PaddleNLP/huggingface/datasets
  TRANSFORMERS_CACHE: /ssd1/PaddleNLP/huggingface

defaults:
  run:
    shell: bash

jobs:
  debug-container:
    name: unittest-gpu-debug
    runs-on: [self-hosted, ernie-8gpu]
    timeout-minutes: 30
    steps:
      - name: Run Container
        env:
          work_dir: ${{ github.workspace }}
          CACHE_DIR: /home/data/cfs/.cache
          FLAGS_dynamic_static_unified_comm: "True"
          python_version: "3.10"
          paddle_whl: https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuSome-LinuxCentos-Gcc82-Cuda118-Cudnn86-Trt85-Py310-CINN-Compile/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> "$GITHUB_ENV"
          image_name=iregistry.baidu-int.com/paddlecloud/base-images:paddlecloud-ubuntu18.04-gcc8.2-cuda11.8-cudnn8.6-nccl2.15.5-latest
          echo "image_name=${image_name}" >> "$GITHUB_ENV"
          docker run -d -t --name ${container_name} --net=host -v /dev/shm:/dev/shm --shm-size=32G \
            -v $work_dir/../../..:$work_dir/../../.. \
            -v $work_dir:/workspace \
            -v /home/.cache/pip:/home/.cache/pip \
            -v /ssd1/PaddleNLP:/ssd1/PaddleNLP \
            -e BRANCH \
            -e PR_ID \
            -e COMMIT_ID \
            -e work_dir \
            -e ci_scripts \
            -e no_proxy \
            -e CI_name \
            -e paddle_whl \
            -e FLAGS_dynamic_static_unified_comm \
            -e python_version \
            -w /workspace --runtime=nvidia $image_name
       
      - name: Download Code
        run: |
          docker exec -t $container_name /bin/bash -c '
          rm -rf * .[^.]*
          echo "Downloading PaddleFormers.tar"
          wget -q --no-proxy  https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddleFormers.tar --no-check-certificate
          echo "Extracting PaddleFormers.tar"
          tar xf PaddleFormers.tar && rm -rf PaddleFormers.tar
          source $work_dir/../../../proxy
          cd PaddleFormers
          git config --global user.name "PaddleCI"
          git config --global user.email "paddle_ci@example.com"
          git pull
          git submodule update --init --recursive --force
          if [ -n "${PR_ID}" ]; then
            git fetch origin pull/${PR_ID}/head
            git checkout -b PR_${PR_ID} FETCH_HEAD
            git remote add upstream https://github.com/PaddlePaddle/PaddleFormers.git
            git fetch upstream ${BRANCH}
            git merge ${BRANCH} --no-edit
            git diff --numstat ${BRANCH} -- | awk "{print \$NF}"
          else
            echo "Not in a pull_request event. Skipping PR-specific operations."
          fi
          git log --pretty=oneline -10
          unset http_proxy && unset https_proxy
          '

      - name: Prepare Environment
        run: |
          docker exec -t $container_name /bin/bash -c '
          ldconfig
          set -e
          unlink /usr/bin/python3
          ln -sf $(which python${python_version}) /usr/bin/python3
          python -c "import sys; print(sys.version_info[:])"
          pip config set global.cache-dir "/home/.cache/pip"
          cd /workspace/PaddleFormers && git config --global --add safe.directory $PWD
          '

      - name: Print Info
        env:
          work_dir: ${{ github.workspace }}
        run: |
          echo "容器已启动，请登录机器进行调试"
          echo "登录机器后，进入容器："
          echo "docker exec -it $container_name bash"
          echo "物理机本地工作目录为：$work_dir/PaddleFormers"
          echo "容器内工作目录为：/workspace/PaddleFormers"
          echo "unittest-gpu任务整体复现命令"
          echo "bash scripts/unit_test/ci_unit.sh ${paddle_whl}"
          echo "也可直接在$work_dir下执行python -m pytest 失败case"
          echo "请调试完成后手动执行清理命令"
          echo "docker rm -f $container_name"